import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

import { DraftModeScript } from '@makeswift/runtime/next/server'

import '@/lib/makeswift/components'
import { MakeswiftProvider } from '@/lib/makeswift/provider'
import { getOptimizelyDatafile } from '@/lib/optimizely/datafile'
import OptimizelyProvider from '@/lib/optimizely/provider'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const sessionId = cookies().get('sessionId')?.value ?? 'session-id'
  const datafile = await getOptimizelyDatafile()

  return (
    <html lang="en">
      <head>
        <DraftModeScript />
      </head>
      <body className={inter.className}>
        <OptimizelyProvider sessionId={sessionId} datafile={datafile}>
          <MakeswiftProvider>{children}</MakeswiftProvider>
        </OptimizelyProvider>
      </body>
    </html>
  )
}
